SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS TB_CMMN_FILE;
DROP TABLE IF EXISTS TB_USER_AUTH;
DROP TABLE IF EXISTS TB_USER;




/* Create Tables */

-- 공통_파일
CREATE TABLE TB_CMMN_FILE
(
	FILE_GRP_ID char(36) NOT NULL COMMENT '파일_그룹_ID',
	FILE_NO int NOT NULL COMMENT '파일_번호',
	ORGN_FILE_NM varchar(256) NOT NULL COMMENT '원본_파일_명',
	CONV_FILE_NM varchar(256) NOT NULL COMMENT '변환_파일_명',
	FILE_SIZE bigint NOT NULL COMMENT '파일_크기',
	FILE_DIV varchar(20) COMMENT '파일_구분',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (FILE_GRP_ID, FILE_NO),
	UNIQUE (FILE_GRP_ID)
) COMMENT = '공통_파일';


-- 사용자
CREATE TABLE TB_USER
(
	USER_ID varchar(50) NOT NULL COMMENT 'USER_ID',
	USER_PW char(64) NOT NULL COMMENT '비밀번호',
	USER_NM varchar(100) NOT NULL COMMENT '사용자 이름',
	PHT_FILE_GRP_ID char(36) COMMENT '사진_파일_그룹_ID',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (USER_ID)
) COMMENT = '사용자';


-- 사용자 권한
CREATE TABLE TB_USER_AUTH
(
	USER_ID varchar(50) NOT NULL COMMENT 'USER_ID',
	USER_AUTH varchar(20) NOT NULL COMMENT '사용자_권한',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (USER_ID, USER_AUTH)
) COMMENT = '사용자 권한';



/* Create Foreign Keys */

ALTER TABLE TB_USER_AUTH
	ADD FOREIGN KEY (USER_ID)
	REFERENCES TB_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



