SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS TB_CMMN_FILE;
DROP TABLE IF EXISTS TB_QNA_REPLY;
DROP TABLE IF EXISTS TB_NOTICE;
DROP TABLE IF EXISTS TB_USER_AUTH;
DROP TABLE IF EXISTS TB_USER;




/* Create Tables */

-- 공통_파일
CREATE TABLE TB_CMMN_FILE
(
	FILE_GRP_ID char(36) NOT NULL COMMENT '파일_그룹_ID',
	FILE_NO int NOT NULL COMMENT '파일_번호',
	ORGN_FILE_NM varchar(256) NOT NULL COMMENT '원본_파일_명',
	CONV_FILE_NM varchar(256) NOT NULL COMMENT '변환_파일_명',
	FILE_SIZE bigint NOT NULL COMMENT '파일_크기',
	FILE_DIV varchar(20) COMMENT '파일_구분',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (FILE_GRP_ID, FILE_NO)
) COMMENT = '공통_파일';


-- 공통게시판
CREATE TABLE TB_NOTICE
(
	NTC_NO int NOT NULL COMMENT '게시판 번호',
	NTC_CTG varchar(100) NOT NULL COMMENT '게시판 종류',
	USER_ID varchar(50) NOT NULL COMMENT 'USER_ID',
	NTC_TTL varchar(500) NOT NULL COMMENT '게시판 제목',
	NTC_CON varchar(3000) NOT NULL COMMENT '게시판 내용',
	NTC_HT varchar(50) COMMENT '게시판 조회수',
	FILE_GRP_ID char(36) COMMENT '파일 그룹 아이디',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (NTC_NO, NTC_CTG),
	UNIQUE (NTC_NO)
) COMMENT = '공통게시판';


-- 문의게시판 답변
CREATE TABLE TB_QNA_REPLY
(
	QNA_RP_NO int NOT NULL COMMENT '문의게시판 답글 번호',
	NTC_NO int NOT NULL COMMENT '게시판 번호',
	NTC_CTG varchar(100) NOT NULL COMMENT '게시판 종류',
	USER_ID varchar(50) NOT NULL COMMENT 'USER_ID',
	QNA_RP_CON varchar(3000) COMMENT '문의게시판 답변 내용',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (QNA_RP_NO),
	UNIQUE (NTC_NO)
) COMMENT = '문의게시판 답변';


-- 사용자
CREATE TABLE TB_USER
(
	USER_ID varchar(50) NOT NULL COMMENT 'USER_ID',
	USER_PW char(64) NOT NULL COMMENT '비밀번호',
	USER_NM varchar(100) NOT NULL COMMENT '사용자 이름',
	PHT_FILE_GRP_ID char(36) COMMENT '사진_파일_그룹_ID',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (USER_ID)
) COMMENT = '사용자';


-- 사용자 권한
CREATE TABLE TB_USER_AUTH
(
	USER_ID varchar(50) NOT NULL COMMENT 'USER_ID',
	USER_AUTH varchar(20) NOT NULL COMMENT '사용자_권한',
	RGST_ID varchar(50) COMMENT '등록_ID',
	RGST_DT datetime DEFAULT NOW() NOT NULL COMMENT '등록_일시',
	UPDT_ID varchar(50) COMMENT '수정_ID',
	UPDT_DT datetime DEFAULT NOW() NOT NULL COMMENT '수정_일시',
	DEL_YN char(1) DEFAULT 'N' NOT NULL COMMENT '삭제_여부',
	PRIMARY KEY (USER_ID, USER_AUTH)
) COMMENT = '사용자 권한';



/* Create Foreign Keys */

ALTER TABLE TB_QNA_REPLY
	ADD FOREIGN KEY (NTC_NO, NTC_CTG)
	REFERENCES TB_NOTICE (NTC_NO, NTC_CTG)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_NOTICE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES TB_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_QNA_REPLY
	ADD FOREIGN KEY (USER_ID)
	REFERENCES TB_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TB_USER_AUTH
	ADD FOREIGN KEY (USER_ID)
	REFERENCES TB_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



